# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openpoet < Formula
  desc "Orchestrate Claude Code sessions across multiple projects"
  homepage "https://github.com/openpoet/openpoet"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.13/openpoet_0.1.13_darwin_amd64.tar.gz"
      sha256 "93e01e34fc8e829e991b353e5a3ec547aa784fc8e33facb508c0a4360a12633a"

      define_method(:install) do
        bin.install "openpoet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.13/openpoet_0.1.13_darwin_arm64.tar.gz"
      sha256 "3d6633a12b692a5787c27e618197f1768ec16fa811367bad8d47361feaac54fd"

      define_method(:install) do
        bin.install "openpoet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.13/openpoet_0.1.13_linux_amd64.tar.gz"
      sha256 "2d7b642d83459e99c0ca1fe3c267812101bd3aeb5dec268f729133e1b993949e"
      define_method(:install) do
        bin.install "openpoet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.13/openpoet_0.1.13_linux_arm64.tar.gz"
      sha256 "81cb13c9a26b00efc4e086f9c54cde745310431ddd5e09bd64d7e9df73c98285"
      define_method(:install) do
        bin.install "openpoet"
      end
    end
  end

  def post_uninstall
    rm_rf "#{Dir.home}/.openpoet"
  end

  def caveats
    <<~EOS
      OpenPoet is ready to use! Start it with:
        openpoet

      The web UI will be available at http://localhost:8080
      Data is stored in ~/.openpoet/

      Note: Node.js 18+ is required for the Claude Agent SDK provider.
      The sidecar scripts are embedded in the binary and auto-extracted on first run.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openpoet version")
  end
end
