# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openpoet < Formula
  desc "Orchestrate Claude Code sessions across multiple projects"
  homepage "https://github.com/openpoet/openpoet"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.0/openpoet_0.1.0_darwin_amd64.tar.gz"
      sha256 "b7db1e8fe1a74c835687ede3489f657c8bed324e87dda25d7a3c8067f38ecda1"

      def install
        bin.install "openpoet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.0/openpoet_0.1.0_darwin_arm64.tar.gz"
      sha256 "40551c74a9d61af3f79a52909429ed54d656ccf7e449598caa170eeb45e369e8"

      def install
        bin.install "openpoet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.0/openpoet_0.1.0_linux_amd64.tar.gz"
      sha256 "2061cc8ebad258f02552d7d3b25cf011bf3c36d8d88a15f2890a862941b10aee"
      def install
        bin.install "openpoet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.0/openpoet_0.1.0_linux_arm64.tar.gz"
      sha256 "589436aac44562ef39f5119896ae07ef5aa1fcf573a33831f829c77094a45085"
      def install
        bin.install "openpoet"
      end
    end
  end

  def caveats
    <<~EOS
      OpenPoet is ready to use! Start it with:
        openpoet

      The web UI will be available at http://localhost:8080

      Note: Node.js 18+ is required for the Claude Agent SDK provider.
      The sidecar scripts are embedded in the binary and auto-extracted on first run.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openpoet version")
  end
end
