# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openpoet < Formula
  desc "Orchestrate Claude Code sessions across multiple projects"
  homepage "https://github.com/openpoet/openpoet"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.2/openpoet_0.1.2_darwin_amd64.tar.gz"
      sha256 "3deef7873e8dd136458ebeefe4f094e0e69b1dca4e695b75e2c50d331c9e55a4"

      def install
        bin.install "openpoet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.2/openpoet_0.1.2_darwin_arm64.tar.gz"
      sha256 "5da5a43eeeffc625fc764e0e4744468adda0bdf00447b6482e4d532412617ad8"

      def install
        bin.install "openpoet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.2/openpoet_0.1.2_linux_amd64.tar.gz"
      sha256 "8879dd7cccb81fb16fc58173dc07b19ef5be242d66fb6700fcf83747ddfb8f32"
      def install
        bin.install "openpoet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openpoet/openpoet/releases/download/v0.1.2/openpoet_0.1.2_linux_arm64.tar.gz"
      sha256 "d3e4c6d7577685fc8e7bc4af8d25c18c6384fe63ab29186f4039770f0f952a30"
      def install
        bin.install "openpoet"
      end
    end
  end

  def caveats
    <<~EOS
      OpenPoet is ready to use! Start it with:
        openpoet

      The web UI will be available at http://localhost:8080

      Note: Node.js 18+ is required for the Claude Agent SDK provider.
      The sidecar scripts are embedded in the binary and auto-extracted on first run.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openpoet version")
  end
end
